version: "3.8"

services:
  mongo_database:
    image: mongo:6.0
    container_name: e-commerce-db
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db
    restart: always

volumes:
  mongo_data:
